name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: Elib2Ebook-${{ matrix.os }}
        path: ${{ github.workspace }}/Elib2Ebook/bin/Release/net6.0/
